# Generated by Django 2.2.1 on 2019-11-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_name', models.CharField(max_length=200, null=True)),
                ('hw_base', models.CharField(max_length=200)),
                ('hw_eval', models.CharField(max_length=200)),
                ('hw_description', models.CharField(max_length=500, null=True)),
                ('hw_duedate', models.DateTimeField(blank=True, null=True)),
                ('hw_madeby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=50)),
                ('professor_name', models.CharField(max_length=50)),
                ('professor_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_number', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Homework_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=50)),
                ('hw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='turninApp.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='CommitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('commit_number', models.CharField(max_length=100)),
                ('commit_message', models.CharField(max_length=100)),
                ('commit_time', models.CharField(max_length=100)),
                ('hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs', to='turninApp.Homework_Student')),
            ],
        ),
    ]
