# Generated by Django 2.2.1 on 2019-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_number', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
            ],
        ),
    ]
