# Generated by Django 2.2.1 on 2019-10-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_name', models.CharField(max_length=200)),
                ('hw_link', models.CharField(max_length=200)),
                ('hw_description', models.CharField(max_length=500)),
                ('duedate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
