# Generated by Django 2.2.1 on 2019-11-04 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_student',
            name='commit_history',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
