# Generated by Django 2.2.6 on 2019-11-07 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0002_homework_student_commit_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework_student',
            old_name='commit_history',
            new_name='commit_message',
        ),
        migrations.AddField(
            model_name='homework_student',
            name='commit_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
