# Generated by Django 2.2.1 on 2019-10-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0002_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='duedate',
        ),
    ]
