# Generated by Django 2.2.3 on 2019-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0004_homework_hw_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=50)),
                ('professor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
