# Generated by Django 2.2.1 on 2019-10-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0005_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_password',
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_status',
            field=models.BooleanField(default=False),
        ),
    ]
