# Generated by Django 2.2.1 on 2019-10-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0007_student_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_password',
        ),
    ]
