# Generated by Django 2.2.1 on 2019-10-18 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0008_remove_student_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='hw_link',
            new_name='hw_base',
        ),
        migrations.AddField(
            model_name='homework',
            name='hw_eval',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
