# Generated by Django 2.2.1 on 2019-10-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0009_auto_20191018_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=50)),
                ('hw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='turninApp.Homework')),
            ],
        ),
    ]
