# Generated by Django 2.2.1 on 2019-10-21 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turninApp', '0010_homework_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_student',
            name='score',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
